### ISSUE TITLE
"--polyglot" option does not appear to be available through the passed gulp options, no es6 support.

### ISSUE THREAD

**Issue by benderTheCrime** [documentationjs/gulp-documentation#5]
Related to this issue:
https://github.com/documentationjs/documentation/issues/112

ES6 documentation cannot be created without the `--polyglot` option. It does not appear as though I can pass this argument via gulp, as demonstrated by my task:

``` javascript
gulp.task('documentation', function() {
    gulp.src(src)
        .pipe(documentation({
            format: 'html',
            polyglot: true
        }))
        .pipe(gulp.dest('md-documentation'));
});
```

and the error I get as a result:

```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: Parsing file *: 'import' and 'export' may appear only with 'sourceType: module' (4:0)
```

but not via the CLI: 
`documentation * --polyglot`

**Comment by tmcw** [comment]
> ES6 documentation cannot be created without the --polyglot option. 

While this repo does need a version bump on its documentation dependency in order to support the --polyglot option, as mentioned on the other ticket: this is a misunderstanding:

* --polyglot is for non-JavaScript code
* Default mode aims to cover ES5 and ES6 code

What you've stumbled on is a bug in espree/ast-types. Once that's fixed, you won't need to pass polyglot as an option.
